# Generated by Django 4.1 on 2022-09-26 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 18, 49, 10, 521843)),
        ),
    ]
